---
title: "R Notebook"
output: html_notebook
runtime: shiny
---

## Library Packages and Load Data

```{r warning=FALSE}
library(lubridate)
library(dplyr)
library(leaflet)
library(shiny)
library(shinyWidgets)
library(shinydashboard)
library(plotly)

# read two datasets
df1 <- read.csv("./NYPD_Arrest_Data__Year_to_Date_.csv")            # year to date data
df2 <- read.csv("./NYPD_Arrests_Data__Historic_.csv")               # historical data

colnames(df1)
colnames(df2)

```

## Combined Raw Datafile

```{r}
df <- df1[,-19] |> 
    rbind(df2[-19]) |> 
    select(ARREST_DATE, OFNS_DESC, LAW_CAT_CD, ARREST_BORO, ARREST_PRECINCT, JURISDICTION_CODE,
           AGE_GROUP, PERP_SEX, PERP_RACE, Latitude, Longitude) |> 
    dplyr::filter(OFNS_DESC != '(null)') |> 
    mutate(ARREST_DATE = as.Date(ARREST_DATE, "%m/%d/%Y"),
           ARREST_YEAR = year(ARREST_DATE))
# diff(range(df$ARREST_DATE))
# length(unique(df$ARREST_DATE))

remove(df1, df2)
head(df)

```

## Prepare data to summary

PreDataTime: A New Database used in Time Serial plot

PreDataPie: A New Database used in Pie plot

```{r}
PreDataTime <- df |> 
    mutate(ARREST_MONTH = month(ARREST_DATE)) |> 
    group_by(ARREST_YEAR, ARREST_MONTH, OFNS_DESC, ARREST_BORO) |> 
    count() |> 
    ungroup() |> 
    dplyr::filter(ARREST_YEAR >= 2011) |> 
    # dplyr::filter(OFNS_DESC != "" & ARREST_BORO != "") |> 
    I()
head(PreDataTime)

PreDataPie <- df |> 
    group_by(ARREST_YEAR, OFNS_DESC, ARREST_BORO, PERP_SEX, PERP_RACE, AGE_GROUP) |> 
    count() |> 
    ungroup() |> 
    dplyr::filter(ARREST_YEAR >= 2011) |> 
    # dplyr::filter(OFNS_DESC != "" & ARREST_BORO != "" & 
    #                   AGE_GROUP %in% c("<18", "18-24", "25-44", "45-64", "65+") &
    #                   PERP_RACE != "UNKNOWN") |> 
    I()
head(PreDataPie)
```

## Value used in Shiny App UI

```{r}
SelectBoro <- unique(PreDataPie$ARREST_BORO)
names(SelectBoro) <- c("Brooklyn", "Manhattan", "Queens", "Bronx", "StatenIsland")
SelectBoro

SelectSex <- c('Male' = 'M', 'Female' = "F")
SelectSex
```

## Shiny APP

```{r}
ui <- shinyUI(
    dashboardPage(
        skin = "red",
        
        dashboardHeader(title = "NYC Arrest Data"),
        
        dashboardSidebar(
            sidebarMenu(
                menuItem("Map", tabName = "Map", icon = icon("map")),
                menuItem("TimeSeries", tabName = "TimeSeries", icon = icon("chart-line")),
                menuItem("PieChart", tabName = "PieChart", icon = icon("chart-pie")),
                menuItem("More Info", tabName = "MoreInfo", icon = icon("info"))
            )
        ),
        
        dashboardBody(
            tags$style(type="text/css",
                       ".shiny-output-error { visibility: hidden; }",
                       ".shiny-output-error:before { visibility: hidden; }"
            ),
            tabItems(
                tabItem(tabName = "Map", 
                        fluidPage(
                            fluidRow(
                                column(6,
                                       selectInput(inputId = "map_year",
                                                   label = "Choose a year",
                                                   selected = 2022,
                                                   choices = seq(min(PreDataTime$ARREST_YEAR),
                                                                 max(PreDataTime$ARREST_YEAR)))
                                ),
                                column(6,
                                       checkboxGroupInput("map_gender", 
                                                          label = "Perpetrator’s gender",
                                                          choices = SelectSex, 
                                                          selected = 'M'),
                                       checkboxGroupInput("map_age", 
                                                          label = "Perpetrator’s age group",
                                                          choices = c('<18','18-24','25-44', '45-64', '65+'),
                                                          selected = '18-24')
                                ),
                                column(12,
                                       leafletOutput("mymap", height = '600px'))
                            )
                        )
                ),
                tabItem(tabName = "TimeSeries",
                        fluidPage(
                            fluidRow(
                                column(6,
                                       selectInput(inputId = "line_year",
                                                   label = "Choose a year",
                                                   selected = 2022,
                                                   choices = seq(min(PreDataTime$ARREST_YEAR),
                                                                 max(PreDataTime$ARREST_YEAR)))
                                ),
                                column(6,
                                       pickerInput(inputId = "line_type",
                                                   label ="choose a type",
                                                   choices = unique(PreDataTime$OFNS_DESC),
                                                   selected = "BURGLARY",
                                                   options = list(
                                                       `actions-box` = TRUE,
                                                       size = 5
                                                   ), 
                                                   multiple = T
                                       ),
                                       pickerInput(inputId = "line_borough",
                                                   label = "choose a borough",
                                                   choices = SelectBoro,
                                                   selected = "Q",
                                                   options = list(
                                                       `actions-box` = TRUE,
                                                       size = 5
                                                   ), 
                                                   multiple = T
                                       )
                                ),
                                column(12,
                                       plotlyOutput(outputId = "ggplot",height = "600px"))
                            )
                        )
                ),
                tabItem(tabName = "PieChart",
                        fluidPage(
                            fluidRow(
                                column(6,
                                       selectInput(inputId = "pie_year",
                                                   label = "Choose a year",
                                                   selected = 2022,
                                                   choices = seq(min(PreDataPie$ARREST_YEAR),
                                                                 max(PreDataPie$ARREST_YEAR)))
                                ),
                                column(6,
                                       pickerInput(inputId = "pie_type",
                                                   label ="choose a type",
                                                   choices = unique(PreDataPie$OFNS_DESC),
                                                   selected = "BURGLARY",
                                                   options = list(
                                                       `actions-box` = TRUE,
                                                       size = 5
                                                   ), 
                                                   multiple = T
                                       ),
                                       pickerInput(inputId = "pie_borough",
                                                   label = "choose a borough",
                                                   choices = SelectBoro,
                                                   selected = "Q",
                                                   options = list(
                                                       `actions-box` = TRUE,
                                                       size = 5
                                                   ), 
                                                   multiple = T
                                       )
                                ),
                            ),
                            column(12,
                                   plotlyOutput("plot", height = '600px'))
                        )
                )
            )
        )
    )
)


server <- shinyServer(function(input, output, session) {
    #### Time Series Graph
  output$ggplot<-renderPlotly({
    Year <- input$line_year
    type <- input$line_type
    borough <- input$line_borough
    
    PreDataTime |> 
        dplyr::filter(ARREST_YEAR == Year &
                          OFNS_DESC %in% type &
                          ARREST_BORO %in% borough) |> 
        group_by(ARREST_MONTH) |> 
        dplyr::summarise(n = sum(n, na.rm = T)) |> 
        ungroup() |> 
        plot_ly(x = ~ARREST_MONTH, 
                y = ~n,
                color = I('black')) |> 
        add_lines(name = '') |> 
        add_markers(name = '',
                    marker = list(size = 10,
                                  color = 'rgba(255, 182, 193, .9)',
                                  line = list(color = 'rgba(152, 0, 0, .8)',
                                              width = 2))) |> 
        layout(showlegend = FALSE,
               xaxis = list(title = list(text = "Month",
                                         font = list(size = 12,
                                                     color = 'black')),
                            dtick = 1,
                            tick0 = 1),
               yaxis = list(title = list(text = "Count",
                                         font = list(size = 12,
                                                     color = 'black'))),
               title = list(text = paste('In', Year,
                                         'the number of', type,
                                         'happened in', names(which(SelectBoro == borough)),
                                         sep = ' '),
                            font = list(size = 14,
                                        color = 'black')))
    })

  ######## Pie Chart Page
  output$plot <- renderPlotly({
    Year <- input$pie_year
    type <- input$pie_type
    borough <- input$pie_borough
    # browser()
    
    DataPlot <- PreDataPie |> 
        dplyr::filter(ARREST_YEAR == Year &
                          OFNS_DESC %in% type &
                          ARREST_BORO %in% borough)
    DataPlotSex <- DataPlot |> 
        group_by(PERP_SEX) |> 
        summarise(n = sum(n, na.rm = T)) |> 
        rename(group = "PERP_SEX") |> 
        mutate(group = case_when(group == 'F' ~ 'Female',
                                 group == 'M' ~ 'Male',
                                 TRUE ~ 'Other'))
    DataPlotRace <- DataPlot |> 
        group_by(PERP_RACE) |> 
        summarise(n = sum(n, na.rm = T)) |> 
        rename(group = "PERP_RACE")
    DataPlotAge <- DataPlot |> 
        group_by(AGE_GROUP) |> 
        summarise(n = sum(n, na.rm = T)) |> 
        rename(group = "AGE_GROUP")
    
    plot_ly() |> 
        add_pie(data = DataPlotSex, labels = ~group, values = ~n,
                textinfo = 'label+percent',
                name = "Sex",
                title = "Perpetrator Sex Distribution Chart",
                marker = list(colors=colors,
                              line = list(color = '#FFFFFF', width = 1)),
                domain = list(x = c(0, 0.4), y = c(0.4, 1))) |> 
        add_pie(data = DataPlotRace, labels = ~group, values = ~ n,
                textinfo = 'label+percent',
                name = "Race",
                showlegend = T,
                title = "Perpetrator Race Distribution Chart",
                marker = list(#colors=colors,
                    line = list(color = '#FFFFFF', width = 1)),
                domain = list(x = c(0.25, 0.75), y = c(0, 0.6))) |> 
        add_pie(data = DataPlotAge, labels = ~group, values = ~ n,
                textinfo = 'label+percent',
                name = "Age",
                title = "Perpetrator Age Distribution Chart",
                marker = list(#colors=colors,
                    line = list(color = '#FFFFFF', width = 1)),
                domain = list(x = c(0.6, 1), y = c(0.4, 1))) %>%
        layout(title = "Pie Chart Summary of Perpetrator Data", showlegend = F,
               #grid=list(rows=1, columns=3),
               xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
               yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  })
  
  ######## Map Page
  output$mymap <- renderLeaflet({
      Year <- input$map_year
      gender <- input$map_gender
      age <- input$map_age
      df |> 
          dplyr::filter(ARREST_YEAR == Year &
                          AGE_GROUP %in% age &
                          PERP_SEX %in% gender) |> 
          leaflet() |> 
          addTiles() |> 
          addCircleMarkers(lng = ~Longitude, lat = ~Latitude, clusterOptions = markerClusterOptions())
  })
})

shinyApp(ui, server)
```

